### PR TITLE
Add APRS to Pip Install and Configure With Command Line

### PR DESCRIPTION
**Pull request by kb1lqc**
# Changelog
* Updated setuptools configuration to create command line function `faraday-aprs`
* Updated setuptools to copy over `aprs.sample.ini` from /etc/faraday to local /etc/faraday folder
* Imported common `loggingConfig.ini` file
* Added command line options for all of `aprs.ini` "APRSIS" section options and only comments in APRS section
  * `--init-config`
  * `--callsign`
  * `--server`
  * `--port`
  * `--rate`
  * `--stationsage`
  * `--comment`
  * `--altcomment`

# Installation
To install please use `pip install -e .` for this PR. Following this, you can view the available command line options and their descriptions by running `faraday-aprs --help` from command line.

### CODE REVIEW

**Comment by kb1lqd** [comment]
* Installed from pip -e
* Configured all as expected (proxy, telemetry, APRS)
* Uploaded APRS data to APRS-IS!

Note @kb1lqc that I could not get the comment text to change...

image


image

**Review by kb1lqd — APPROVED** [review]
APRS installed via pip as expected and uploaded data to the APRS-IS server(s). Review of the code shows expected updates and no obvious errors/issues.

**Comment by kb1lqc** [comment]
@kb1lqd you need to change the `altcomment`. Reading the `--help` you can see that `altcomment` is the access point comment while `comment` is for the node.

image

**Comment by kb1lqc** [comment]
Setting the `altcomment`:
image

Results:
image

**Pull request merged**
