### PR TITLE
Renamed proxy folder to Proxy

### PR DESCRIPTION
**Pull request by Amrithasuresh**
Hi,

As per the suggestion https://github.com/FaradayRF/Faraday-Software/issues/99 #114, I have renamed the proxy folder to uppercase. Hope this helps. 

I don't own a Faraday radio.  @kb1lqc @kb1lqd Please test this. Thank you.

### CODE REVIEW

**Comment by kb1lqc** [comment]
Thanks @Amrithasuresh looking at this now!

**Review by kb1lqc — CHANGES_REQUESTED** [review]
Hey @Amrithasuresh I noticed that the file move is registering as all the files completely changing from proxy to Proxy folders. However it is in such a way that the moved files are counted as new additions, therefore all content is marked as additions.

This make it hard to review since all code is treated as brand new (green highlights).

The proper way to do this is `git mv` and it results in Git knowing that these files did not change but were only renamed. Could you try doing that will a clean checkout of master?

https://githowto.com/moving_files

One trick to know is you will not be able to perform `git mv proxy/ Proxy/` as git will complain you don't have permission. This is because proxy and Proxy are the same to Git at this time. The solution is to move to a temporary folder

- `git mv proxy/ proxy-tmp/`
- `git mv proxy-tmp/ Proxy/`

**Comment by Amrithasuresh** [comment]
@kb1lqc Yeah. I will do it and update you. Thank you.

**Comment by Amrithasuresh** [comment]
@kb1lqc I have deleted the repository and did a fresh fork. I committed changes as per your suggestion. What should I do now? Do I need to create another pull request?. Thank you.

**Comment by kb1lqc** [comment]
Yes @Amrithasuresh making a new PR might be the easiest thing to do. Just copy the main info from this one that you put in the Summary. Thanks!

**Comment by kb1lqc** [comment]
PR #127 supersedes this PR.

**Pull request closed without merging**
