### PR TITLE
Fix for issue #148 - add CORS support to Telemetry.

### PR DESCRIPTION
**Pull request by jsr38**
Add CORS support to Telemetry.  Have updated requirements.txt to include the new dependency.  Tested in as far as I can start the server with the same result as before but cannot (easily) currently check for the presence of CORS HTTP headers.

### CODE REVIEW

**Comment by jsr38** [comment]
I see the CI build failed, rightly due to:  

/home/travis/build/FaradayRF/Faraday-Software/Applications/Telemetry/telemetry.py:25:1: F401 'flask_cors.cross_origin' imported but unused

To avoid this in future, what do I need to do to enable strict checking or to run the CI check itself before I submit?

**Comment by kb1lqc** [comment]
@jsr38 you should run it locally prior before submitting the PR but totally OK right now. Yes I forgot to mention this will not be used until I pull in #145. Therefore I'll manually check to see if this is correctly implemented and will pull it immediately after #145 and cite the necessary merge.

**Review by kb1lqc — APPROVED** [review]
These look great! Will pull in once #145 is implemented and ready to pull into master.

**This branch will fail Travic-CI until #145 is merged which actually uses CORS**

**Comment by jsr38** [comment]
Of course I at least ran it ;-)  I'd like to know how I can run it with the strict checks (warnings -> failure promotion) equivalent to the way CI invokes it, locally.  Something to do with PEP8?  I can probably figure it out but I'm wondering if there's a pattern.  Something about  FLAKE8-check(ignoring E262 E265 E266 E402 E501).  I'm not familiar with the CI setup.  Is it possible to get a suitably modified "py.test" to run locally?

**Review by kb1lqc — APPROVED** [review]
Tested this updated code with cross_origin removed using hardware and my simple user interface program which requires CORS and it works fine.

**Pull request merged**
