### PR TITLE
aprs-readme

### PR DESCRIPTION
**Pull request by brw32**
Hi. Updated the info about the Passcode automatically generated.

Issue #147

### CODE REVIEW

**Review by kb1lqc — APPROVED** [review]
Looks great. Thanks for the contribution!

**Comment by brw32** [comment]
Thanks, Bryce. My first pull request!!

**Comment by kb1lqc** [comment]
@bwittig32 congrats! We're super happy to be your first open source project contribution on GitHub!

**Comment by brw32** [comment]
Me too!!  Thanks again, VERY MUCH!!

**Pull request merged**
